# Generated by Django 5.2.5 on 2025-11-04 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Club Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "club_type",
                    models.CharField(
                        choices=[
                            ("LITERARY", "Literary Club"),
                            ("WRITING", "Writing Club"),
                            ("BOOK_CLUB", "Book Club"),
                            ("STUDY_GROUP", "Study Group"),
                        ],
                        default="BOOK_CLUB",
                        max_length=20,
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Max Members"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Private Club"),
                ),
                (
                    "meeting_schedule",
                    models.JSONField(
                        default=dict, help_text="Meeting schedule information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founded_clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(default=20, verbose_name="Max Members"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="groups.club",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Group",
                "verbose_name_plural": "Club Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(default=50, verbose_name="Max Members"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Private Group"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reading_groups",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Group",
                "verbose_name_plural": "Reading Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("FILE", "File"),
                            ("SYSTEM", "System"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="groups.club",
                    ),
                ),
                (
                    "club_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="groups.clubgroup",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_group_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_group_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reading_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="groups.readinggroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["reading_group", "created_at"],
                        name="groups_mess_reading_bdbfcc_idx",
                    ),
                    models.Index(
                        fields=["club", "created_at"],
                        name="groups_mess_club_id_26d722_idx",
                    ),
                    models.Index(
                        fields=["club_group", "created_at"],
                        name="groups_mess_club_gr_11b648_idx",
                    ),
                    models.Index(
                        fields=["sender", "recipient", "created_at"],
                        name="groups_mess_sender__2c8a49_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("MODERATOR", "Moderator"),
                            ("ADMIN", "Admin"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.readinggroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
                "ordering": ["joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
