# Generated by Django 5.2.5 on 2025-11-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Conversation Title"
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Chat"),
                            ("WRITING", "Writing Assistance"),
                            ("EDITING", "Editing Help"),
                            ("RESEARCH", "Research Help"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Additional context information"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                (
                    "related_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.personalbook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Conversation",
                "verbose_name_plural": "AI Conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ASSISTANT", "Assistant"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "model_used",
                    models.CharField(default="gpt-3.5-turbo", max_length=50),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aiconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Message",
                "verbose_name_plural": "AI Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("total_conversations", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "features_used",
                    models.JSONField(default=dict, help_text="Usage by feature type"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Tracking",
                "verbose_name_plural": "AI Usage Tracking",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
