# Generated by Django 5.2.5 on 2025-09-03 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ALERT', 'Alerte'), ('SUCCESS', 'Succès')], default='INFO', max_length=20, verbose_name='Type de notification')),
                ('status', models.CharField(choices=[('UNREAD', 'Non lu'), ('READ', 'Lu')], default='UNREAD', max_length=20, verbose_name='Statut')),
                ('related_url', models.URLField(blank=True, verbose_name='URL liée')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Envoyé à')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
