# Generated by Django 5.2.5 on 2025-11-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_initial"),
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("total_borrows", models.PositiveIntegerField(default=0)),
                ("total_reservations", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("average_reading_time", models.DurationField(blank=True, null=True)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "daily_stats",
                    models.JSONField(default=dict, help_text="Daily statistics"),
                ),
                (
                    "monthly_stats",
                    models.JSONField(default=dict, help_text="Monthly statistics"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Analytics",
                "verbose_name_plural": "Book Analytics",
            },
        ),
        migrations.CreateModel(
            name="SalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sales", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "price_history",
                    models.JSONField(default=list, help_text="Price change history"),
                ),
                ("sales_by_country", models.JSONField(default=dict)),
                ("sales_by_region", models.JSONField(default=dict)),
                ("daily_sales", models.JSONField(default=dict)),
                ("monthly_sales", models.JSONField(default=dict)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "personal_book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_analytics",
                        to="books.personalbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Analytics",
                "verbose_name_plural": "Sales Analytics",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("BOOK_VIEW", "Book View"),
                            ("DOWNLOAD", "Download"),
                            ("SEARCH", "Search"),
                            ("USER_ACTION", "User Action"),
                            ("SYSTEM_EVENT", "System Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=100, verbose_name="Event Name"),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, help_text="Additional event data"),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_a_event_t_6c35be_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_a_user_id_ecb128_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="Activity Type"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional activity metadata"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Activity duration", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.book",
                    ),
                ),
                (
                    "personal_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.personalbook",
                    ),
                ),
                (
                    "reading_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="groups.readinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type", "created_at"],
                        name="analytics_u_user_id_11191e_idx",
                    )
                ],
            },
        ),
    ]
