# Generated by Django 5.2.5 on 2025-11-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job d'Export (Legacy)",
                "verbose_name_plural": "Jobs d'Export (Legacy)",
            },
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_export_jobs",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_export_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="exportjob",
            table="export_jobs_legacy",
        ),
    ]
