# Generated by Django 5.2.5 on 2025-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_exportjob_options_alter_exportjob_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("VISITOR", "Visitor"),
                    ("STUDENT", "Student"),
                    ("PROFESSOR", "Professor"),
                    ("LIBRARIAN", "Librarian"),
                    ("ADMIN", "Administrator"),
                ],
                default="VISITOR",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
