# Generated by Django 5.2.5 on 2025-11-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Format Name"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "file_extension",
                    models.CharField(max_length=10, verbose_name="File Extension"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "requires_premium",
                    models.BooleanField(default=False, verbose_name="Requires Premium"),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Max File Size (MB)"
                    ),
                ),
                (
                    "default_template",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Default Template"
                    ),
                ),
                (
                    "supported_features",
                    models.JSONField(
                        default=list, help_text="Supported features for this format"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Export Format",
                "verbose_name_plural": "Export Formats",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                            ("epub", "EPUB"),
                            ("txt", "Plain Text"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "options",
                    models.JSONField(default=dict, help_text="Options d'exportation"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progression en pourcentage"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job d'Export",
                "verbose_name_plural": "Jobs d'Export",
                "db_table": "export_jobs_new",
                "ordering": ["-created_at"],
            },
        ),
    ]
