# Generated by Django 5.2.5 on 2025-10-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_reports', to='books.book'),
        ),
        migrations.AddField(
            model_name='readingreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['user', 'book'], name='notificatio_user_id_e61a65_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['rating'], name='notificatio_rating_d2c7de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='notificatio_sender__5e00f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='notificatio_timesta_9e1e38_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='readingreport',
            index=models.Index(fields=['user', 'book'], name='notificatio_user_id_1ff062_idx'),
        ),
        migrations.AddIndex(
            model_name='readingreport',
            index=models.Index(fields=['created_at'], name='notificatio_created_fa6bb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingreport',
            unique_together={('user', 'book')},
        ),
    ]
