# Generated by Django 5.2.5 on 2025-09-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('CARD', 'Carte bancaire'), ('CASH', 'Espèces'), ('TRANSFER', 'Virement')], default='CARD', max_length=20, verbose_name='Méthode de paiement')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='ID de paiement Stripe')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
