# Generated by Django 5.2.5 on 2025-09-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('RESERVED', 'Réservé'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires totaux')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Auteurs')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
    ]
