# Generated by Django 5.2.5 on 2025-10-28 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réservation')),
                ('expiry_date', models.DateTimeField(verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('READY', 'Prêt à être récupéré'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Complété')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('due_date', models.DateTimeField(verbose_name='Date de retour prévue')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('status', models.CharField(choices=[('BORROWED', 'Emprunté'), ('RETURNED', 'Retourné'), ('OVERDUE', 'En retard')], default='BORROWED', max_length=20, verbose_name='Statut')),
                ('renewed', models.BooleanField(default=False, verbose_name='Renouvelé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.book', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
