# Generated by Django 5.2.5 on 2025-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/uploaded_files/')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image File'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSourceFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='OpenSource')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('document', models.FileField(blank=True, null=True, upload_to='books_files/opensources/', verbose_name='PDF_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('can_download', models.BooleanField(default=True, verbose_name='Peut télécharger')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='personal_book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé'), ('DELETED', 'Supprimé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mots')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de caractères')),
                ('document', models.FileField(blank=True, null=True, upload_to='personal_book_files/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('can_download', models.BooleanField(default=False, verbose_name='Peut télécharger')),
            ],
            options={
                'verbose_name': 'Livre personnel',
                'verbose_name_plural': 'Livres personnels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Subcategories',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Thèse')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('RESERVED', 'Réservé'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('document', models.FileField(blank=True, null=True, upload_to='books_files/theses/', verbose_name='PDF_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('can_download', models.BooleanField(default=False, verbose_name='Peut télécharger')),
            ],
            options={
                'verbose_name': 'Thèse',
                'verbose_name_plural': 'Thèses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('RESERVED', 'Réservé'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('document', models.FileField(blank=True, null=True, upload_to='books_files/', verbose_name='PDF_files')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires totaux')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('can_download', models.BooleanField(default=False, verbose_name='Peut télécharger')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Auteurs')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('RESERVED', 'Réservé'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mots')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de caractères')),
                ('document', models.FileField(blank=True, null=True, upload_to='books_files/articles/', verbose_name='PDF_files')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('can_download', models.BooleanField(default=False, verbose_name='Peut télécharger')),
                ('authors', models.ManyToManyField(related_name='articles', to='books.author', verbose_name='Auteurs')),
                ('categories', models.ManyToManyField(related_name='articles', to='books.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ebook')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('RESERVED', 'Réservé'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('document', models.FileField(blank=True, null=True, upload_to='books_files/ebooks/', verbose_name='PDF_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('can_download', models.BooleanField(default=False, verbose_name='Peut télécharger')),
                ('authors', models.ManyToManyField(related_name='ebooks', to='books.author', verbose_name='Auteurs')),
                ('categories', models.ManyToManyField(related_name='ebooks', to='books.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title'],
            },
        ),
    ]
