# Generated by Django 5.2.5 on 2025-10-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opensourcefiles',
            name='authors',
            field=models.ManyToManyField(related_name='open_sources', to='books.author', verbose_name='Auteurs'),
        ),
        migrations.AddField(
            model_name='opensourcefiles',
            name='categories',
            field=models.ManyToManyField(related_name='open_sources', to='books.category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='personalbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_books', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCategorie', to='books.category', verbose_name='subCategorie'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='authors',
            field=models.ManyToManyField(related_name='theses', to='books.author', verbose_name='Auteurs'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='categories',
            field=models.ManyToManyField(related_name='theses', to='books.category', verbose_name='Catégories'),
        ),
    ]
