# Generated by Django 5.2.5 on 2025-09-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='personal_book_covers/', verbose_name='Image de couverture')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mots')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de caractères')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_books', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Livre personnel',
                'verbose_name_plural': 'Livres personnels',
                'ordering': ['-created_at'],
            },
        ),
    ]
